name: Go package

concurrency:
  group: Test
  cancel-in-progress: true

on: [push]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    environment: Test
    strategy:
      matrix:
        go-version: ['1.18.x']
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Install dependencies
        run: go get .
      
      - name: Build and validate
        run: |
          go build -v ./...
        
      - name: Manual check
        uses: peter-evans/check.txt@v1.4.0
        with:
          path: check.txt
          
      - name: Push code
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          directory: ./
          github_token: ${{ secrets.GITHUB_TOKEN }}
