name: Go package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Add your build and validation steps here
      
      # Add a manual approval step
      - name: Manual approval
        if: always()
        uses: peter-evans/wait-on-check@v2
        with:
          status: "success"
          check_name: "Build and validate"
          wait_time: 300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
