name: Go package

concurrency:
  group: Test
  cancel-in-progress: true

on: [push]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    environment: Test
    strategy:
      matrix:
        go-version: ['1.18.x']
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Install dependencies
        run: go get .
      
      - name: Build and validate
        run: |
          go build -v ./...
          go vet ./...
      
      # Add a manual approval step
      - name: Manual approval
        if: always()
        uses: peter-evans/wait-on-check@v2
        with:
          status: "success"
          check_name: "Manual approval"
          wait_time: 300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Add a step to push the code if the check is approved
      - name: Push code
        if: always() && success()
        run: |
          git add .
          git commit -m "Update code"
          git push
