name: Go package

concurrency:
  group: Test
  cancel-in-progress: true

on: [ main ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      GOROOT: /usr/local/go
      GOPATH: ${{ runner.workspace }}/go
      PATH: ${{ env.GOROOT }}/bin:${{ env.GOPATH }}/bin:${{ env.PATH }}
    strategy:
      matrix:
        go-version: ['1.18.x']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Install dependencies
        run: go mod download
      
      - name: Build
        run: go build -v ./...
        
      - name: Create check.txt
        run: echo "Please verify that everything is working correctly." > check.txt
        
      - name: Manual check
        uses: peter-evans/wait-on-check@v1.4.0
        with:
          path: check.txt
          
      - name: Push code
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          directory: ./
          github_token: ${{ secrets.GITHUB_TOKEN }}
