name: Go package with manual check

on: [push]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    environment: Test
    strategy:
      matrix:
        go-version: ['1.18.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Manual Check
        run: echo "Please perform a manual check"

      - name: Push Code
        if: github.event_name == 'push' && success()
        env:
          TARGET_BRANCH: "production"
        run: |
          git checkout -b $Test || git checkout $Test
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push -u origin $Test